### ISSUE TITLE
About Pixiv Tile

### ISSUE THREAD

**Issue by Crossady** [PixeezPlusProject/PixivUniversal#1]
It seems every time I click Pixiv Tile it will shows Error.
Hopefully it can be fixed.
Thank you guys for such a good UWP

**Comment by TobiichiAmane** [comment]
Received. But the changing of Microsoft Store's policy made us unable to update the app anymore. We are negotiating with Microsoft, hope to solve the problem.

**Comment by IHateGFW** [comment]
还有WPF版的开发计划吗？
