### ISSUE TITLE
Problem with loading BlankPage.

### ISSUE THREAD

**Issue by Pshpdesu** [PixeezPlusProject/PixivUniversal#10]
On load of the BlankPage InitializeComponent throw an exception with message "XAML parsing failed".
Then I commented "gotoBox" AutoSuggestBox, the problem disappeared.

**Comment by TobiichiAmane** [comment]
We cannot reproduce this bug, but since this AutoSuggestBox has never been enabled, commented it out won't cause any problems. 
Since a lot of users of ours have been suffering from a mysterious bug causing their not being able to login, we've made the product unavailable on MS Store, until we solve the problem. Actually, we cannot reproduce this bug neither, even on 10 more different devices. Even in China where Pixiv has been blocked for a little while, my users can still login through proxy. So, if you can reproduce this bug, that causes your not being able to login, please contact us through GitHub issues, or email. It'll be appreciated.

**Comment by Pshpdesu** [comment]
I also have encountered problem with login, so I decided to try build app from sources. When I tried to login, program tried to open BlankPage. MasterDetailControl tries to Navigate BlankPage to DetailContentPresenter. MasterDetailControl called by pg_Main's constructor. After I commented "gotoBox" parser error disappeared.

Same problem with BlankPage occurs then I tried to press back button after login (also after multiple clicks on it). Same error as before - "XAML parser error" in the "BlankPage" constructor. 
Text of the exception then initializing components of BlankPage:
`{Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed.    at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)    at PixivUWP.Pages.DetailPage.BlankPage.InitializeComponent()    at PixivUWP.Pages.DetailPage.BlankPage..ctor()} | Windows.UI.Xaml.Markup.XamlParseException`

I have second PC, where I can't login. Tried to debug it. Same exceptions in BlankPage, as I described at the beginning of this message.

Text of the Exception for exception in MasterDetailControl:
`
Windows.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=The text associated with this error code could not be found.

Cannot create instance of type 'PixivUWP.Pages.MasterDetailControl' [Line: 33 Position: 51]
  Source=Windows
  StackTrace:
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at PixivUWP.Pages.pg_Main.InitializeComponent() in C:\Users\pavel\Source\Repos\PixivUniversal\PixivUWP\obj\x86\Debug\Pages\pg_Main.g.i.cs:line 41
   at PixivUWP.Pages.pg_Main..ctor() in C:\Users\pavel\Source\Repos\PixivUniversal\PixivUWP\Pages\pg_Main.xaml.cs:line 51
   at PixivUWP.PixivUWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_34_pg_Main() in C:\Users\pavel\Source\Repos\PixivUniversal\PixivUWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 350
   at PixivUWP.PixivUWP_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\Users\pavel\Source\Repos\PixivUniversal\PixivUWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 1118
`
All that exceptions are caught by try-catch in BeginLoading, what leads to problems with authorization.

If you want I can try to record video with this.

**Comment by TobiichiAmane** [comment]
Thanks a lot for figuring out what causes the bug and how to fix it, but we just can't reproduce it. Pretty strange. You can fork this repo, solve it, and give us a pull request. After we merge it, you'll be listed as a contributor. Thanks again.

**Comment by Pshpdesu** [comment]
I think I finally found a problem. You missed gotoBox.PlaceholderText localization in Strings/en-US/Resources.resw. Because of what you and your friends can't reproduce it (Chinese interface language?)

**Comment by TobiichiAmane** [comment]
Exactly! We all use Chinese as our display language and China/Japan as our region. This must be the exact problem that causes all the failures. Thanks a lot for figuring it out.

**Comment by TobiichiAmane** [comment]
Problem fixed.
