### ISSUE TITLE
在后台自动登陆每次都会收到异地登陆警告邮件

### ISSUE THREAD

**Issue by AkazaDorian** [PixeezPlusProject/PixivUniversal#12]
> ## [pixiv] 有新的登入活动 (位置: 日本)
>
> XXX先生小姐、您好。
> 我们是pixiv事务局。
> 
> 您使用的pixiv帐号(pixiv ID:my_pixiv_id, 用户ID:number)有新的登入活动，因此寄送这封电子邮件通知您。
> 
> 位置: 日本
> 时间: 2018年6月30日 13:52 (日本时间)
> IP位址: 172.105.x.x
> 
> 从2016年12月31日开始，為了强化帐户安全，因此寄送这封电子邮件通知您。
> 
> ■是帐户本人登入的
> 感谢您的确认。没有必要做特别的动作。请您继续使用pixiv。
> 
> 这是您首次透过新电脑、手机、瀏览器登入帐户；您是透过瀏览器的无痕模式或私密模式登入帐户，或是在清除Cookie、瀏览纪录后才登入帐户，因此会寄送这封电子邮件给您。
> 
> ■对这个登入活动没有印象吗？
> 可能有第叁者「盗用」登入您的帐户。
> 為了您的帐户安全，请至以下网址确认您的登入活动纪录，如果您对这个登入活动没有印象的话，请更改密码。

一天大概能收到十几封吧

**Comment by TobiichiAmane** [comment]
因为我们至今没搞清楚Pixiv的官方客户端是怎么刷新登录的，所以每次登录超时之后都需要全新登录一次，这就会产生大量的登录邮件。自动登录是为了刷新动态磁贴，如果不需要动态磁贴功能，可以去系统设置里停用该应用的后台。

**Comment by AkazaDorian** [comment]
@TobiichiAmane 我已经停用了……但是依然会收到邮件

**Comment by TobiichiAmane** [comment]
那应该只会产生于你手动启动应用时。

**Comment by AkazaDorian** [comment]
@TobiichiAmane 印象里有时候我一整天都没有启动过却依然收到了邮件，但是可能是由于某种原因导致被关闭的后台重新启动了。我会再测试一段时间看看。

**Comment by AkazaDorian** [comment]
@TobiichiAmane https://github.com/alphasp/pxview
这个应用是我在安卓端上使用的，没有遇到过异地登录的情况，希望能有所启发。

**Comment by TobiichiAmane** [comment]
嗯。在我们解决之前，在这里关掉后台应该不会有新的自动登录产生。
![image](https://user-images.githubusercontent.com/14824064/42122013-8c7213ec-7c6d-11e8-9959-a5d5a0706b7e.png)
