### ISSUE TITLE
Constant Mail login notifications

### ISSUE THREAD

**Issue by Charmandrigo** [PixeezPlusProject/PixivUniversal#13]
Is there a way to fix that constant email login notification from Pixiv?
It has to do with the background update feature, it can get annoying getting the same "New Login to pixiv" mail every certain minutes, even when the app is closed, I can get about 5 mail notifications per Windows session

**Comment by TobiichiAmane** [comment]
You can disable its background task via system setting to prevent the app from logging in automatically, but after which it won't be able to refresh its tile. We have not figured it out how to refresh an auth token yet, which causes the problem.
![image](https://user-images.githubusercontent.com/14824064/42306633-5cb0189a-8062-11e8-8a3e-5bbec81a5a29.png)

**Comment by TobiichiAmane** [comment]
Duplicate to #12 .
