### ISSUE TITLE
Update button

### ISSUE THREAD

**Issue by Pshpdesu** [PixeezPlusProject/PixivUniversal#15]
If you try to update list by pressing on refresh button after some usage (for 15 minute or so), list of works will be empty. Same thing with detail part of window.

**Comment by Pshpdesu** [comment]
Same situation with changing tab from one to another (from recommended page to bookmarks or ranking, for example).

**Comment by TobiichiAmane** [comment]
I'm quite busy currently, and this project may be discontinued. Maybe I can give you the permission so you can commit to this repo directly if you want? Sorry for discontinuing this project but I'm currently working on Arch Linux CN repo which consumes me a lot of my spare time...

**Comment by Pshpdesu** [comment]
Maybe I will try to do something with it in fork, but not really sure. Don't have enough experience with UWP and other stuff

**Comment by TobiichiAmane** [comment]
OK. I'll leave this issue open. Maybe I'll try to fix it if I have time.

**Comment by Pshpdesu** [comment]
At some point httpClient.GetAsync(uri) in SendRequestWithoutHeaderAsync returning StatusCode: 400 without reason.
uri: 
`https://app-api.pixiv.net/v1/illust/recommended?content_type=illust&include_ranking_label=true&filter=for_ios`

response:
```
{StatusCode: 400, 
ReasonPhrase: '', 
Version: 2.0, 
Content: System.Net.Http.StreamContent, 
Headers:
{  
server: nginx  
strict-transport-security: 
max-age=31536000  
date: Sat, 10 Nov 2018 11:59:19 GMT 
 x-content-type-options: nosniff  
content-length: 189  
content-type: application/json; charset=utf-8
}
}
```

**Comment by yinyue200** [comment]
@Pshpdesu maybe we can add codes to force the app refresh the token when the error occur

**Comment by Pshpdesu** [comment]
@yinyue200  Maybe, but pixiv will start to sending emails about login into it. As in the case of tile update.

**Comment by yinyue200** [comment]
@Pshpdesu Are you sure it always send an email after login. In my device, it not.

**Comment by yinyue200** [comment]
@Pshpdesu I think a email is better than a empty page😂

**Comment by Pshpdesu** [comment]
@Pshpdesu Yes, but anyway it's pretty annoying 🤔
