### ISSUE TITLE
Loading order for works with multiple image

### ISSUE THREAD

**Issue by Pshpdesu** [PixeezPlusProject/PixivUniversal#16]
Images in "Full Size"window loading in strange order. Pictures may be duplicated several times, or arranged in wrong order.

**Comment by SakuraNeko** [comment]
@Pshpdesu Thanks, I need some time to determine the problem.

**Comment by TobiichiAmane** [comment]
@SakuraNeko I'm currently working on Arch CN repo now, you are on your own.

**Comment by yinyue200** [comment]
I can't reproduce this problem.
https://1drv.ms/u/s!Aukoh90qxXKSosJv69x65NxJFFM2HA
https://www.pixiv.net/member_illust.php?mode=manga&illust_id=69589494

**Comment by Pshpdesu** [comment]
Maybe this occurs with collections what contains more than 3 pictures?
https://1drv.ms/u/s!AiWnXUFBbRcw2qN1TSLX_EQ8GlEdlQ

**Comment by yinyue200** [comment]
@Pshpdesu try this patch #17

**Comment by Pshpdesu** [comment]
Same thing, but now if picture duplicates, it changing to correct image after process complete it's loading (?)

**Comment by yinyue200** [comment]
@Pshpdesu please try the latest update

**Comment by yinyue200** [comment]
@Pshpdesu Did you try it https://github.com/PixeezPlusProject/PixivUniversal/pull/17/commits/ac1919c56960433881062d2b9e46854f873bcf00

**Comment by yinyue200** [comment]
@Pshpdesu There are three way to achieve it. image cache in memory ,image cache in disk(like a web browser) , increase the itemspanel.cachelength

**Comment by Pshpdesu** [comment]
Maybe make a separate issue for this and close this one?
