### ISSUE TITLE
下载的时候会闪退

### ISSUE THREAD

**Issue by YefengYue** [PixeezPlusProject/PixivUniversal#3]
我点击图片下面的“下载”按钮，以及下载页面下方的“下载文件夹”按钮都会闪退，请问这个是什么原因？【我试着在C:\Users\YefengYue\Pictures里新建了一个Pixiv文件夹，依然会闪退

**Comment by TobiichiAmane** [comment]
emmmmm目前没有类似的报告。你有能力自己编译并调试一下源码嘛x，dev分支下的，如果可以的话，可以告诉我哪儿抛出了什么异常嘛x

**Comment by yyf512845135** [comment]
诶。。。我那自己先动手先试试，python用户并没用用过C#，有新发现再反馈

**Comment by TobiichiAmane** [comment]
emmmmmm其实最近很多境外用户报告了各种Bug，但是内测人员一个都没遇到x所以本来打算做个log系统的，现在还没空动工（怀孕了家人不让爆肝x所以先麻烦你自行手动收集一下异常情况x

**Comment by yyf512845135** [comment]
来了来了！！！
报错位置pg_Download.xaml.cs的193行
private async void AppBarButton_Click(object sender, RoutedEventArgs e)
{
    await Data.DownloadManager.getpicfolder();
    await Launcher.LaunchFolderAsync(Data.DownloadManager.pictureFolder);
}


输出窗口输出：
引发的异常:“System.NullReferenceException”(位于 PixivUWP.exe 中)
NullException
loadAsync() called.
“PixivUWP.exe”(CoreCLR: CoreCLR_UWP_Domain): 已加载“D:\PixivUniversal-developing\PixivUWP\bin\x86\Debug\AppX\TileBackground.winmd”。已加载符号。
Access token: XsRd6USOHJ-zc0_Zh3XRqtfAi_VL9kfBzWgFsaIgU4s
“PixivUWP.exe”(CoreCLR: CoreCLR_UWP_Domain): 已加载“D:\PixivUniversal-developing\PixivUWP\bin\x86\Debug\AppX\System.Numerics.Vectors.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“PixivUWP.exe”(CoreCLR: CoreCLR_UWP_Domain): 已加载“D:\PixivUniversal-developing\PixivUWP\bin\x86\Debug\AppX\System.ValueTuple.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“PixivUWP.exe”(CoreCLR: CoreCLR_UWP_Domain): 已加载“D:\PixivUniversal-developing\PixivUWP\bin\x86\Debug\AppX\Microsoft.Toolkit.Uwp.Notifications.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
loadAsync() called.
“PixivUWP.exe”(CoreCLR: CoreCLR_UWP_Domain): 已加载“C:\Program Files\WindowsApps\Microsoft.Services.Store.Engagement_10.0.17112.0_x86__8wekyb3d8bbwe\Microsoft.Services.Store.Engagement.winmd”。模块已生成，不包含符号。
“PixivUWP.exe”(CoreCLR: CoreCLR_UWP_Domain): 已加载“D:\PixivUniversal-developing\PixivUWP\bin\x86\Debug\AppX\System.Xml.ReaderWriter.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
引发的异常:“System.NullReferenceException”(位于 PixivUWP.exe 中)
引发的异常:“System.Runtime.InteropServices.COMException”(位于 System.Private.CoreLib.ni.dll 中)
引发的异常:“System.Runtime.InteropServices.COMException”(位于 System.Private.CoreLib.ni.dll 中)
“System.Runtime.InteropServices.COMException”类型的异常在 System.Private.CoreLib.ni.dll 中发生，但未在用户代码中进行处理
未指定的错误



报错详细信息：
System.Runtime.InteropServices.COMException
  HResult=0x80004005
  Message=未指定的错误

  Source=System.Private.CoreLib
  StackTrace:
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 PixivUWP.Data.DownloadManager.<getpicfolder>d__3.MoveNext() 在 D:\PixivUniversal-developing\PixivUWP\Data\DownloadManager.cs 中: 第 87 行
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 PixivUWP.Pages.pg_Download.<AppBarButton_Click>d__12.MoveNext() 在 D:\PixivUniversal-developing\PixivUWP\Pages\pg_Download.xaml.cs 中: 第 193 行

**Comment by yyf512845135** [comment]
有看了一下，似乎是文件夹没有正确的创建。

运行DownloadManager.cs的第87行时出错
public static async Task getpicfolder()
        {
            if (pictureFolder == null)
                pictureFolder = await Windows.Storage.KnownFolders.PicturesLibrary.CreateFolderAsync("Pixiv", CreationCollisionOption.OpenIfExists);
        }
我不清楚这个CreateFolderAsync究竟是怎么运行的，要靠你们惹XD

ps：另外我再我另外一台笔记本上就没有发生这个错误，会不会是windows版本的问题？出问题的是家庭版，可以正常运行的是专业版。

**Comment by yinyue200** [comment]
@YefengYue 要不你联系一下我，你看看你电脑的图片库是不是正常的

**Comment by YefengYue** [comment]
@yinyue200 哇怎么联系？我并不是很会用github，有私信吗？
另外我看似乎是文件夹Pixiv根本就没获取到，我在图片文件夹里手动创建了一个Pixiv，但是运行到getpicfolder()时，pictureFolder是null

**Comment by yinyue200** [comment]
@YefengYue 我也不知道你怎么联系我好，GitHub没私信

**Comment by YefengYue** [comment]
@yinyue200 nescafe233@163.com

**Comment by yinyue200** [comment]
@YefengYue 邮箱回复你了

**Comment by yinyue200** [comment]
问题已解决，图片库设置仅设置 OneDrive 文件夹导致的
