### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by Charmandrigo** [PixeezPlusProject/PixivUniversal#7]
Despite having my Pixiv login credentials right, Pixiv UWP keeps saying the username or password was wrong, when this was not the case as I get via email the pixiv notification of a new login, every time I try to access it says I have typed my credentials wrong

**Comment by TobiichiAmane** [comment]
@Charmandrigo  This bug is caused by a json parser we use in the code. We may reconstruct all json parsing code to try to fix this issue.

**Comment by SakuraNeko** [comment]
Please see if our updated version resolves your problem in the next few days. If the problem persists please let us know here.

**Comment by SakuraNeko** [comment]
@Charmandrigo Please see if our updated version resolves your problem in the next few days. If the problem persists please let us know here.

**Comment by TobiichiAmane** [comment]
In issue #10 @Pshpdesu has found and solved the bug. We'll update our package for MS Store as soon as possible.

**Comment by Charmandrigo** [comment]
Hello, I downloaded the app from my Store app library
The problem is still not fixed, same issue happened, login attempt failed on the app yet I got the Pixiv mail notification of my login attempt.
I should note I am trying to login from Mexico, I'm not sure if this has something to do with the place I am trying to log
![785687](https://user-images.githubusercontent.com/30424766/42063957-d523c952-7af9-11e8-84b5-6b4daf285419.png)

**Comment by TobiichiAmane** [comment]
![image](https://user-images.githubusercontent.com/14824064/42070684-324bba96-7b8a-11e8-9270-12443c0e13df.png)
Our commit is still being validated by MS Store. Please be patient.

**Comment by TobiichiAmane** [comment]
Published. You can try again.
